/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const blob_delete: (a: number, b: number) => [number, number];
export const blob_get: (a: number, b: number) => [number, number, number, number];
export const blob_put: (a: number, b: number, c: number, d: number) => [number, number];
export const boot: () => any;
export const prepare_http_send: (a: any) => any;
export const rpc: (a: number, b: number, c: any, d: number, e: number) => [number, number, number];
export const rust_sqlite_wasm_abort: () => void;
export const rust_sqlite_wasm_assert_fail: (a: number, b: number, c: number, d: number) => void;
export const rust_sqlite_wasm_calloc: (a: number, b: number) => number;
export const rust_sqlite_wasm_free: (a: number) => void;
export const rust_sqlite_wasm_getentropy: (a: number, b: number) => number;
export const rust_sqlite_wasm_localtime: (a: number) => number;
export const rust_sqlite_wasm_malloc: (a: number) => number;
export const rust_sqlite_wasm_realloc: (a: number, b: number) => number;
export const sqlite3_os_end: () => number;
export const sqlite3_os_init: () => number;
export const wasm_bindgen_c2918f11b6912c75___convert__closures_____invoke___wasm_bindgen_c2918f11b6912c75___JsValue__core_7eb07022c2a3a7a___result__Result_____wasm_bindgen_c2918f11b6912c75___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c2918f11b6912c75___convert__closures_____invoke___web_sys_b5afd8de14b549da___features__gen_IdbVersionChangeEvent__IdbVersionChangeEvent__core_7eb07022c2a3a7a___result__Result_____wasm_bindgen_c2918f11b6912c75___JsValue___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c2918f11b6912c75___convert__closures_____invoke___js_sys_1764129d0fc3e4e5___Function_fn_wasm_bindgen_c2918f11b6912c75___JsValue_____wasm_bindgen_c2918f11b6912c75___sys__Undefined___js_sys_1764129d0fc3e4e5___Function_fn_wasm_bindgen_c2918f11b6912c75___JsValue_____wasm_bindgen_c2918f11b6912c75___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_c2918f11b6912c75___convert__closures_____invoke___web_sys_b5afd8de14b549da___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_c2918f11b6912c75___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
